@url = https://8080-yurizin4-securitytutori-zxlbpyffea6.ws-us118.gitpod.io

@token = 

GET {{url}}/categorias
Authorization:  Bearer {{token}}

###
POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Ciencias Exatas"
}