@url = 

@token = 

GET {{url}}/categorias
Authorization:  Bearer {{token}}

###
POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Ciencias Exatas"
}