@url = https://8080-yurizin4-securitytutori-zxlbpyffea6.ws-us118.gitpod.io
@token = 

GET {{url}}/opcoes
Authorization: Bearer {{token}}

###
GET {{url}}/opcoes/1
Authorization: Bearer {{token}}

###
POST {{url}}/opcoes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "texto": "Paris",
    "correta": true,
    "questao": {
        "id": 1
    }
}