@url = https://8080-yurizin4-securitytutori-zxlbpyffea6.ws-us118.gitpod.io 
@token = 

POST {{url}}/usuarios
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nomeDeUsuario" : "nono",
    "senha" : "testando"
}